# Generated by Django 5.0.6 on 2024-07-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_shopuser_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopuser",
            name="is_customer",
        ),
        migrations.RemoveField(
            model_name="shopuser",
            name="is_vendor",
        ),
    ]
