# Generated by Django 5.0.6 on 2024-06-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_rename_customer_notificationrequest_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationrequest",
            options={"verbose_name_plural": "notifications"},
        ),
    ]
