# Generated by Django 5.0.6 on 2024-07-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_notificationrequest_back_in_stock_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Smartphones", "Smartphones"),
                    ("Laptops", "Laptops"),
                    ("Tablets", "Tablets"),
                    ("Televisions", "Televisions"),
                    ("Cameras", "Cameras"),
                    ("Headphones", "Headphones"),
                    ("Smartwatches", "Smartwatches"),
                    ("Gaming Consoles", "Gaming Consoles"),
                    ("Drones", "Drones"),
                    ("Accessories", "Accessories"),
                    ("Others", "Others"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
