# Generated by Django 5.0.6 on 2024-07-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="prod_images/default.jpg", upload_to="prod_images/"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Smartphones", "Smartphones"),
                    ("Laptops", "Laptops"),
                    ("Tablets", "Tablets"),
                    ("Televisions", "Televisions"),
                    ("Cameras", "Cameras"),
                    ("Headphones", "Headphones"),
                    ("Smartwatches", "Smartwatches"),
                    ("Gaming Consoles", "Gaming Consoles"),
                    ("Drones", "Drones"),
                    ("Accessories", "Accessories"),
                    ("More", "More"),
                ],
                default="More",
                max_length=20,
            ),
        ),
    ]
