# Generated by Django 5.0.6 on 2024-07-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_product_image_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="prod_images/"),
        ),
    ]
