# Generated by Django 5.0.6 on 2024-07-02 15:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_notificationrequest_read"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="notificationrequest",
            unique_together={("product", "user")},
        ),
    ]
