# Generated by Django 5.0.6 on 2024-07-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_alter_notificationrequest_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[("Pending", "pending"), ("Confirmed", "confirmed")],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
