# Generated by Django 5.0.6 on 2024-07-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_alter_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="prod_images/default.jpg", upload_to="prod_images/"
            ),
        ),
    ]
